from typing import Protocol

class LLMProvider(Protocol):
    async def summarize(self, content: str) -> str: ...
    async def extract_topics(self, content: str) -> list[str]: ...
    async def analyze_trends(self, contents_with_ids: str, time_range: str) -> str: ...
